Repository InfAurora/TypeScript-Projects, pull requests merged in 2021-10, with the labels that each got.

#51 Issue-50 create decision doc
  simple-blog/README.md
  simple-blog/documentation/technical-decisions.md
Labels: documentation

#52 Issue 44 create login modal
  simple-blog/src/app/app.component.spec.ts
  simple-blog/src/app/app.module.ts
  simple-blog/src/app/blog-dialogs/login-dialog/login-dialog.component.html
  simple-blog/src/app/blog-dialogs/login-dialog/login-dialog.component.sass
  simple-blog/src/app/blog-dialogs/login-dialog/login-dialog.component.spec.ts
  simple-blog/src/app/blog-dialogs/login-dialog/login-dialog.component.ts
  simple-blog/src/app/blog-navbar/blog-navbar.component.html
  simple-blog/src/app/blog-navbar/blog-navbar.component.spec.ts
  simple-blog/src/app/blog-navbar/blog-navbar.component.ts
Labels: feature

#58 Issue-45 create signup btn
  simple-blog/src/app/blog-navbar/blog-navbar.component.html
  simple-blog/src/app/blog-navbar/blog-navbar.component.sass
Labels: feature

#60 Created menu icon, that also has a drop down
  simple-blog/src/app/app.component.spec.ts
  simple-blog/src/app/app.module.ts
  simple-blog/src/app/blog-navbar/blog-navbar.component.html
  simple-blog/src/app/blog-navbar/blog-navbar.component.sass
  simple-blog/src/app/blog-navbar/blog-navbar.component.spec.ts
Labels: Enhancement
