Repository InfAurora/TypeScript-Projects, pull requests merged in 2021-09, with the labels that each got.

#1 PR-test branch
  .github/workflows/main.yml
  simple-blog/package.json
  simple-blog/src/app/app.component.html
  simple-blog/src/app/app.component.spec.ts
Labels: enhancement

#2 Created build:prod command
  simple-blog/package.json
Labels: enhancement

#11 Pipeline update to use hyphen
  .github/workflows/main.yml
  README.md
Labels: documentation, Enhancement

#13 Created buildspec.yml
  simple-blog/buildspec.yml
Labels: Enhancement

#15 added curly backets
  simple-blog/buildspec.yml
Labels: Enhancement

#16 Create PULL_REQUEST_TEMPLATE.md
  .github/workflows/PULL_REQUEST_TEMPLATE.md
Labels: documentation, feature

#17 Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation, feature

#18 deleted old pr temp from wrong pathway
  .github/workflows/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#25 issue-24 updated buildspec to checkout master and pull develop in if tests pass
  simple-blog/buildspec.yml
Labels: Enhancement

#31 Issue-3 abstract navbar
  .github/pull_request_template.md
  README.md
  simple-blog/src/app/app.component.html
  simple-blog/src/app/app.component.sass
  simple-blog/src/app/app.component.spec.ts
  simple-blog/src/app/blog-navbar/blog-navbar.component.html
  simple-blog/src/app/blog-navbar/blog-navbar.component.sass
  simple-blog/src/app/blog-navbar/blog-navbar.component.spec.ts
Labels: Refactor

#39 Issue-38 create variables sass
  simple-blog/package-lock.json
  simple-blog/package.json
  simple-blog/src/styles.sass
  simple-blog/src/variables.sass
Labels: Enhancement
